import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "../libs/providers";
import { ToastProvider } from '@/src/components/ui/toast';
import { Toaster } from '@/src/components/ui/sonner';
import "./globals.css";
import SmoothScroll from "../comPonent/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll />
        <ToastProvider>
          <Providers>{children}</Providers>
          <Toaster />
        </ToastProvider>
      </body>
    </html>
  );
}
